src/main/java/com/bluelotussoftware/jsf/example/IndexBean.java
/*
 *
 * Copyright 2013 Blue Lotus Software LLC. All Rights Reserved.
 *
 * $Id$
 *
 */
package com.bluelotussoftware.jsf.example;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author John Yeary <jyeary@bluelotussoftware.com>
 * @version 1.0
 */
@ManagedBean
@RequestScoped
public class IndexBean {

    public IndexBean() {
    }

    public String getRequestURL() {
        return "other";
    }
}

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <f:metadata>
        <f:viewParam name="color" value="color:blue;"/>
    </f:metadata>
    <h:outputStylesheet name="default.css" library="css"/>
    <h:head>
        <title>Index</title>
    </h:head>
    <h:body>
        <a class="formatted" href="faces/other.xhtml">Other</a>
        <br/>
        <h:link disabled="true" value="X" styleClass="formatted" 
                outcome="other"/>
        <br/>
        <h:link rendered="false" value="Y" outcome="other"/>
        <br/>
        <h:link value="Press CTRL+ALT+M" accesskey="M" outcome="#{indexBean.requestURL}" 
                styleClass="formatted"/>
        <br/>
        <h:link value="Z" outcome="other" />
        <br/>
        <h:link accesskey="E" outcome="other" includeViewParams="true"/>
    </h:body>
</html>

src/main/webapp/other.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <f:metadata>
            <f:viewParam name="color"/>
        </f:metadata>
    </h:head>
    <h:body>
        <h:outputText value="Hello World" style="#{color}"/>
    </h:body>
</html>